spring:
  docker:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.docker-compose.spring.docker.compose.enabled
    compose:
      enabled: true
      file:
      host:
      lifecycle-management: start-and-stop
      profiles:
        active:
      readiness:
        timeout: 2m
        wait: always
        tcp:
          connect-timeout: 200ms
          read-timeout: 200ms
      skip:
        in-tests: true
      start:
        command: up
        log-level: info
      stop:
        command: stop
        timeout: 10s
