<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.zero</groupId>
  <artifactId>micro-service-demo</artifactId>
  <version>1.0.0</version>

  <packaging>pom</packaging>
  <modules>
    <module>common</module>
    <module>gateway</module>
    <module>iam</module>
    <module>basic</module>
  </modules>

  <name>micro-service-demo</name>
  <description>微服务 Demo</description>

  <properties>
    <!-- properties -->
    <java.version>1.8</java.version>
    <project.encoding>UTF-8</project.encoding>
    <resource.delimiter>@</resource.delimiter>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.encoding>${project.encoding}</maven.compiler.encoding>
    <project.build.sourceEncoding>${project.encoding}</project.build.sourceEncoding>
    <project.reporting.outputEncoding>${project.encoding}</project.reporting.outputEncoding>

    <!-- dependencies -->
    <common.version>1.0.0</common.version>
    <!-- spring dependencies -->
    <spring-framework.version>5.3.34</spring-framework.version>
    <spring-boot.version>2.7.18</spring-boot.version>
    <spring-cloud.version>2021.0.9</spring-cloud.version>
    <spring-cloud-alibaba.version>2021.0.5.0</spring-cloud-alibaba.version>
    <spring-cloud-huawei.version>1.11.0-2021.0.x</spring-cloud-huawei.version>
    <spring-cloud-azure.version>4.14.0</spring-cloud-azure.version>
    <spring-cloud-netflix.version>3.1.8</spring-cloud-netflix.version>
    <spring-shell.version>2.1.7</spring-shell.version>
    <spring-data.version>2021.2.17</spring-data.version>
    <spring-integration.version>5.5.19</spring-integration.version>
    <spring-security.version>5.7.11</spring-security.version>
    <spring-session.version>2021.2.3</spring-session.version>

    <!-- starter dependencies -->
    <dubbo.version>3.2.9</dubbo.version>
    <spring-boot-admin.version>2.7.14</spring-boot-admin.version>
    <springdoc.version>2.5.0</springdoc.version>
    <druid.version>1.2.16</druid.version>
    <dynamic-datasource.version>4.2.0</dynamic-datasource.version>
    <mybatis.version>2.3.0</mybatis.version>
    <mybatis-plus.version>3.5.4.1</mybatis-plus.version>
    <mybatis-flex.version>1.7.5</mybatis-flex.version>
    <arthas.version>3.4.8</arthas.version>
    <shiro.version>1.9.1</shiro.version>
    <redisson.version>3.19.3</redisson.version>
    <jasypt-starter.version>3.0.5</jasypt-starter.version>
    <powerjob.version>4.3.0</powerjob.version>
    <elasticjob.version>3.0.4</elasticjob.version>
    <devh-grpc.version>2.15.0.RELEASE</devh-grpc.version>
    <lock4j.version>2.2.5</lock4j.version>
    <sa-token.version>1.37.0</sa-token.version>
    <dynamic-tp.verison>1.1.4.1</dynamic-tp.verison>
    <jetcache.version>2.7.3</jetcache.version>
    <!-- component dependencies -->
    <jasypt.version>1.9.3</jasypt.version>
    <txlcn.version>5.0.2.RELEASE</txlcn.version>
    <xxl-job.version>2.3.1</xxl-job.version>
    <apollo.version>2.1.0</apollo.version>
    <x-file-storage.version>2.0.0</x-file-storage.version>
    <minio.version>8.5.2</minio.version>
    <swagger.version>2.2.15</swagger.version>
    <flyway.version>8.5.13</flyway.version>
    <!-- util dependencies -->
    <hutool.version>5.8.22</hutool.version>
    <guava.version>31.1-jre</guava.version>
    <gson.version>2.10.1</gson.version>
    <kaptcha.version>2.3.2</kaptcha.version>
    <fastjson.version>1.2.83</fastjson.version>
    <fastjson2.version>2.0.26</fastjson2.version>
    <transmittable-thread-local.version>2.14.2</transmittable-thread-local.version>
    <disruptor.version>3.4.4</disruptor.version>
    <mapstruct.version>1.5.5.Final</mapstruct.version>
    <lombok-mapstruct-binding.version>0.2.0</lombok-mapstruct-binding.version>
    <!-- other dependencies -->
    <mysql.version>8.0.32</mysql.version>
    <grpc.version>1.59.0</grpc.version>
    <protobuf.version>3.24.4</protobuf.version>

    <!-- extensions -->
    <os-plugin.version>1.7.1</os-plugin.version>

    <!-- plugins -->
    <maven-antrun-plugin.version>3.0.0</maven-antrun-plugin.version>
    <maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
    <maven-clean-plugin.version>3.2.0</maven-clean-plugin.version>
    <maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
    <maven-dependency-plugin.version>3.3.0</maven-dependency-plugin.version>
    <maven-deploy-plugin.version>2.8.2</maven-deploy-plugin.version>
    <maven-enforcer-plugin.version>3.0.0</maven-enforcer-plugin.version>
    <maven-failsafe-plugin.version>2.22.2</maven-failsafe-plugin.version>
    <maven-help-plugin.version>3.2.0</maven-help-plugin.version>
    <maven-install-plugin.version>2.5.2</maven-install-plugin.version>
    <maven-invoker-plugin.version>3.2.2</maven-invoker-plugin.version>
    <maven-jar-plugin.version>3.2.2</maven-jar-plugin.version>
    <maven-javadoc-plugin.version>3.4.1</maven-javadoc-plugin.version>
    <maven-resources-plugin.version>3.2.0</maven-resources-plugin.version>
    <maven-shade-plugin.version>3.3.0</maven-shade-plugin.version>
    <maven-source-plugin.version>3.2.1</maven-source-plugin.version>
    <maven-surefire-plugin.version>2.22.2</maven-surefire-plugin.version>
    <maven-war-plugin.version>3.3.2</maven-war-plugin.version>
    <spring-boot-plugin.version>${spring-boot.version}</spring-boot-plugin.version>
    <spring-javaformat-plugin.version>0.0.35</spring-javaformat-plugin.version>
    <build-helper-maven-plugin.version>3.3.0</build-helper-maven-plugin.version>
    <dependency-management-plugin.version>1.0.15.RELEASE</dependency-management-plugin.version>
    <git-commit-id-plugin.version>4.9.10</git-commit-id-plugin.version>
    <versions-maven-plugin.version>2.10.0</versions-maven-plugin.version>
    <xml-maven-plugin.version>1.0.2</xml-maven-plugin.version>
    <protobuf-plugin.version>0.6.1</protobuf-plugin.version>
    <docker-plugin.version>0.42.0</docker-plugin.version>
  </properties>

  <!-- 全局依赖 -->
  <dependencies>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <dependencyManagement>
    <dependencies>
      <!-- Common -->
      <dependency>
        <groupId>org.zero</groupId>
        <artifactId>common-bom</artifactId>
        <version>${common.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Framework -->
      <!-- https://spring.io/projects/spring-framework -->
      <!-- https://mvnrepository.com/artifact/org.springframework/spring-framework-bom -->
      <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-framework-bom</artifactId>
        <version>${spring-framework.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Boot -->
      <!-- https://spring.io/projects/spring-boot -->
      <!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies -->
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Cloud -->
      <!-- https://spring.io/projects/spring-cloud -->
      <!-- https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-dependencies -->
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>${spring-cloud.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Data -->
      <!-- https://spring.io/projects/spring-data -->
      <!-- https://mvnrepository.com/artifact/org.springframework.data/spring-data-bom -->
      <dependency>
        <groupId>org.springframework.data</groupId>
        <artifactId>spring-data-bom</artifactId>
        <version>${spring-data.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Integration -->
      <!-- https://spring.io/projects/spring-integration -->
      <!-- https://mvnrepository.com/artifact/org.springframework.integration/spring-integration-bom -->
      <dependency>
        <groupId>org.springframework.integration</groupId>
        <artifactId>spring-integration-bom</artifactId>
        <version>${spring-integration.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Shell -->
      <!-- https://spring.io/projects/spring-shell -->
      <!-- https://mvnrepository.com/artifact/org.springframework.shell/spring-shell-dependencies -->
      <dependency>
        <groupId>org.springframework.shell</groupId>
        <artifactId>spring-shell-dependencies</artifactId>
        <version>${spring-shell.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Security -->
      <!-- https://spring.io/projects/spring-security -->
      <!-- https://mvnrepository.com/artifact/org.springframework.security/spring-security-bom -->
      <dependency>
        <groupId>org.springframework.security</groupId>
        <artifactId>spring-security-bom</artifactId>
        <version>${spring-security.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Session -->
      <!-- https://spring.io/projects/spring-session -->
      <!-- https://mvnrepository.com/artifact/org.springframework.session/spring-session-bom -->
      <dependency>
        <groupId>org.springframework.session</groupId>
        <artifactId>spring-session-bom</artifactId>
        <version>${spring-session.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Cloud Alibaba -->
      <dependency>
        <groupId>com.alibaba.cloud</groupId>
        <artifactId>spring-cloud-alibaba-dependencies</artifactId>
        <version>${spring-cloud-alibaba.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Cloud Huawei -->
      <dependency>
        <groupId>com.huaweicloud</groupId>
        <artifactId>spring-cloud-huawei-bom</artifactId>
        <version>${spring-cloud-huawei.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Cloud Azure -->
      <dependency>
        <groupId>com.azure.spring</groupId>
        <artifactId>spring-cloud-azure-dependencies</artifactId>
        <version>${spring-cloud-azure.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Cloud Netflix -->
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-netflix-dependencies</artifactId>
        <version>${spring-cloud-netflix.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Spring Boot Admin -->
      <dependency>
        <groupId>de.codecentric</groupId>
        <artifactId>spring-boot-admin-dependencies</artifactId>
        <version>${spring-boot-admin.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Hutool -->
      <dependency>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-bom</artifactId>
        <version>${hutool.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Dubbo -->
      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-bom</artifactId>
        <version>${dubbo.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

      <!-- Hutool（工具集） -->
      <dependency>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-all</artifactId>
        <version>${hutool.version}</version>
      </dependency>
      <!-- Guava（工具集） -->
      <!-- https://github.com/google/guava -->
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>${guava.version}</version>
      </dependency>
      <!-- Kaptcha（图形验证码） -->
      <dependency>
        <groupId>com.google.code</groupId>
        <artifactId>kaptcha</artifactId>
        <version>${kaptcha.version}</version>
      </dependency>
      <!-- Kaptcha（图形验证码） -->
      <!-- 因为google-kaptcha不在maven中央仓库，所以使用三方包 -->
      <dependency>
        <groupId>com.github.penggle</groupId>
        <artifactId>kaptcha</artifactId>
        <version>${kaptcha.version}</version>
      </dependency>
      <!-- gson（json） -->
      <!-- https://github.com/google/gson/blob/main/UserGuide.md -->
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>${gson.version}</version>
      </dependency>
      <!-- fastjson（json） -->
      <!-- https://github.com/alibaba/fastjson/wiki/Quick-Start-CN -->
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>fastjson</artifactId>
        <version>${fastjson.version}</version>
      </dependency>
      <!-- fastjson2（json） -->
      <!-- https://github.com/alibaba/fastjson2/blob/main/README.md -->
      <dependency>
        <groupId>com.alibaba.fastjson2</groupId>
        <artifactId>fastjson2</artifactId>
        <version>${fastjson2.version}</version>
      </dependency>
      <!-- transmittable-thread-local（TTL） -->
      <!-- https://github.com/alibaba/transmittable-thread-local#-user-guide -->
      <!-- 处理线程池线程变量不能共用的情况 -->
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>transmittable-thread-local</artifactId>
        <version>${transmittable-thread-local.version}</version>
      </dependency>
      <!-- Disruptor -->
      <!-- https://lmax-exchange.github.io/disruptor/ -->
      <dependency>
        <groupId>com.lmax</groupId>
        <artifactId>disruptor</artifactId>
        <version>${disruptor.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <!-- 资源 -->
    <resources>
      <!-- 定义classpath下需要引用的资源文件 -->
      <resource>
        <directory>${basedir}/src/main/java</directory>
        <includes>
          <include>**/*.xml</include>
          <include>**/*.dtd</include>
          <include>**/*.ftl</include>
          <include>**/*.json</include>
        </includes>
      </resource>

      <!-- 需要进行预编译的资源文件 -->
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <filtering>true</filtering>
        <includes>
          <include>**/application*.yml</include>
          <include>**/application*.yaml</include>
          <include>**/application*.properties</include>
        </includes>
      </resource>
      <!-- 排除预编译的资源文件后需要包含的文件 -->
      <resource>
        <directory>${basedir}/src/main/resources</directory>
        <excludes>
          <exclude>**/application*.yml</exclude>
          <exclude>**/application*.yaml</exclude>
          <exclude>**/application*.properties</exclude>
        </excludes>
      </resource>
    </resources>

    <!-- 扩展 -->
    <extensions>
      <!-- 获取与平台相关的项目属性 -->
      <!-- https://github.com/trustin/os-maven-plugin -->
      <extension>
        <groupId>kr.motd.maven</groupId>
        <artifactId>os-maven-plugin</artifactId>
        <version>${os-plugin.version}</version>
      </extension>
    </extensions>

    <!-- 插件 -->
    <plugins>
      <!-- 项目版本管理 -->
      <!-- https://www.mojohaus.org/versions/versions-maven-plugin/index.html -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <configuration>
          <!-- 无需备份pom文件 -->
          <generateBackupPoms>false</generateBackupPoms>
        </configuration>
      </plugin>
      <!-- 单元测试 -->
      <!-- https://maven.apache.org/surefire/maven-surefire-plugin/ -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <configuration>
          <!-- 跳过单测 -->
          <skip>true</skip>
        </configuration>
      </plugin>
    </plugins>

    <!-- 插件管理 -->
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${build-helper-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.flywaydb</groupId>
          <artifactId>flyway-maven-plugin</artifactId>
          <version>${flyway.version}</version>
        </plugin>
        <plugin>
          <groupId>pl.project13.maven</groupId>
          <artifactId>git-commit-id-plugin</artifactId>
          <version>${git-commit-id-plugin.version}</version>
          <executions>
            <execution>
              <goals>
                <goal>revision</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <verbose>true</verbose>
            <dateFormat>yyyy-MM-dd'T'HH:mm:ssZ</dateFormat>
            <generateGitPropertiesFile>true</generateGitPropertiesFile>
            <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties
            </generateGitPropertiesFilename>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.johnzon</groupId>
          <artifactId>johnzon-maven-plugin</artifactId>
          <version>${johnzon.version}</version>
        </plugin>
        <plugin>
          <groupId>org.jooq</groupId>
          <artifactId>jooq-codegen-maven</artifactId>
          <version>${jooq.version}</version>
        </plugin>
        <plugin>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-maven-plugin</artifactId>
          <version>${kotlin.version}</version>
          <configuration>
            <jvmTarget>${java.version}</jvmTarget>
            <javaParameters>true</javaParameters>
          </configuration>
          <executions>
            <execution>
              <id>compile</id>
              <phase>compile</phase>
              <goals>
                <goal>compile</goal>
              </goals>
            </execution>
            <execution>
              <id>test-compile</id>
              <phase>test-compile</phase>
              <goals>
                <goal>test-compile</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.liquibase</groupId>
          <artifactId>liquibase-maven-plugin</artifactId>
          <version>${liquibase.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-antrun-plugin</artifactId>
          <version>${maven-antrun-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-assembly-plugin</artifactId>
          <version>${maven-assembly-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-clean-plugin</artifactId>
          <version>${maven-clean-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${maven-compiler-plugin.version}</version>
          <configuration>
            <parameters>true</parameters>
            <!-- 预编译 -->
            <annotationProcessorPaths>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
              </path>
              <path>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok-mapstruct-binding</artifactId>
                <version>${lombok-mapstruct-binding.version}</version>
              </path>
              <path>
                <groupId>org.mapstruct</groupId>
                <artifactId>mapstruct-processor</artifactId>
                <version>${mapstruct.version}</version>
              </path>
              <!-- MyBatis-Flex提供的APT服务 -->
              <path>
                <groupId>com.mybatis-flex</groupId>
                <artifactId>mybatis-flex-processor</artifactId>
                <version>${mybatis-flex.version}</version>
              </path>
            </annotationProcessorPaths>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-dependency-plugin</artifactId>
          <version>${maven-dependency-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${maven-deploy-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-enforcer-plugin</artifactId>
          <version>${maven-enforcer-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-failsafe-plugin</artifactId>
          <version>${maven-failsafe-plugin.version}</version>
          <executions>
            <execution>
              <goals>
                <goal>integration-test</goal>
                <goal>verify</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <classesDirectory>${project.build.outputDirectory}</classesDirectory>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-help-plugin</artifactId>
          <version>${maven-help-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-install-plugin</artifactId>
          <version>${maven-install-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-invoker-plugin</artifactId>
          <version>${maven-invoker-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${maven-jar-plugin.version}</version>
          <configuration>
            <archive>
              <manifest>
                <!--suppress UnresolvedMavenProperty -->
                <mainClass>${start-class}</mainClass>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${maven-javadoc-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>${maven-resources-plugin.version}</version>
          <configuration>
            <propertiesEncoding>${project.build.sourceEncoding}</propertiesEncoding>
            <delimiters>
              <delimiter>${resource.delimiter}</delimiter>
            </delimiters>
            <useDefaultDelimiters>false</useDefaultDelimiters>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-shade-plugin</artifactId>
          <version>${maven-shade-plugin.version}</version>
          <configuration>
            <keepDependenciesWithProvidedScope>true</keepDependenciesWithProvidedScope>
            <createDependencyReducedPom>true</createDependencyReducedPom>
            <filters>
              <filter>
                <artifact>*:*</artifact>
                <excludes>
                  <exclude>META-INF/*.SF</exclude>
                  <exclude>META-INF/*.DSA</exclude>
                  <exclude>META-INF/*.RSA</exclude>
                </excludes>
              </filter>
            </filters>
          </configuration>
          <dependencies>
            <dependency>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-maven-plugin</artifactId>
              <version>${spring-boot-plugin.version}</version>
            </dependency>
          </dependencies>
          <executions>
            <execution>
              <phase>package</phase>
              <goals>
                <goal>shade</goal>
              </goals>
              <configuration>
                <transformers>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                    <resource>META-INF/spring.handlers</resource>
                  </transformer>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                    <resource>META-INF/spring.schemas</resource>
                  </transformer>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                    <resource>
                      META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
                    </resource>
                  </transformer>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                    <resource>
                      META-INF/spring/org.springframework.boot.actuate.autoconfigure.web.ManagementContextConfiguration.imports
                    </resource>
                  </transformer>
                  <transformer
                    implementation="org.springframework.boot.maven.PropertiesMergingResourceTransformer">
                    <resource>META-INF/spring.factories</resource>
                  </transformer>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                  <transformer
                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                    <!--suppress UnresolvedMavenProperty -->
                    <mainClass>${start-class}</mainClass>
                  </transformer>
                </transformers>
              </configuration>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${maven-source-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>${maven-surefire-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-war-plugin</artifactId>
          <version>${maven-war-plugin.version}</version>
          <configuration>
            <archive>
              <manifest>
                <!--suppress UnresolvedMavenProperty -->
                <mainClass>${start-class}</mainClass>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <!-- https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/ -->
        <plugin>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-maven-plugin</artifactId>
          <version>${spring-boot-plugin.version}</version>
          <executions>
            <execution>
              <id>repackage</id>
              <goals>
                <goal>repackage</goal>
              </goals>
            </execution>
          </executions>
          <configuration>
            <!--suppress UnresolvedMavenProperty -->
            <mainClass>${start-class}</mainClass>
            <excludes>
              <exclude>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
              </exclude>
            </excludes>
          </configuration>
          <!-- spring boot fat jar 瘦身 - 方式2（不建议使用） -->
          <!--<dependencies>
              <dependency>
                  <groupId>org.springframework.boot.experimental</groupId>
                  <artifactId>spring-boot-thin-layout</artifactId>
                  <version>1.0.31.RELEASE</version>
              </dependency>
          </dependencies>-->
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${versions-maven-plugin.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>xml-maven-plugin</artifactId>
          <version>${xml-maven-plugin.version}</version>
        </plugin>
        <!-- spring boot fat jar 瘦身 - 方式1 -->
        <!-- https://github.com/spring-projects-experimental/spring-boot-thin-launcher/blob/main/README.md -->
        <plugin>
          <groupId>org.springframework.boot.experimental</groupId>
          <artifactId>spring-boot-thin-maven-plugin</artifactId>
          <version>1.0.31.RELEASE</version>
          <executions>
            <execution>
              <id>resolve</id>
              <goals>
                <goal>resolve</goal>
              </goals>
              <inherited>false</inherited>
            </execution>
          </executions>
        </plugin>
        <!-- 编译proto文件 -->
        <!-- https://www.xolstice.org/protobuf-maven-plugin/index.html -->
        <plugin>
          <groupId>org.xolstice.maven.plugins</groupId>
          <artifactId>protobuf-maven-plugin</artifactId>
          <version>${protobuf-plugin.version}</version>
          <configuration>
            <pluginId>grpc-java</pluginId>
            <!-- 工具 -->
            <protocArtifact>com.google.protobuf:protoc:${protobuf.version}:exe:${os.detected.classifier}
            </protocArtifact>
            <pluginArtifact>io.grpc:protoc-gen-grpc-java:${grpc.version}:exe:${os.detected.classifier}
            </pluginArtifact>
            <!-- proto源文件路径 -->
            <protoSourceRoot>${project.basedir}/src/main/proto</protoSourceRoot>
            <!-- proto目标java文件路径 -->
            <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
            <!-- 设置是否在生成java文件之前清空outputDirectory的文件，默认值为true。设置为false时也会覆盖同名文件 -->
            <clearOutputDirectory>false</clearOutputDirectory>
          </configuration>
          <executions>
            <execution>
              <phase>compile</phase>
              <goals>
                <!-- 生成OuterClass类 -->
                <goal>compile</goal>
                <!-- 生成Grpc类 -->
                <goal>compile-custom</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <!-- Docker构建集成 -->
        <!-- https://dmp.fabric8.io/ -->
        <plugin>
          <groupId>io.fabric8</groupId>
          <artifactId>docker-maven-plugin</artifactId>
          <version>${docker-plugin.version}</version>
          <configuration>
            <!-- Docker远程守护进程URL -->
            <dockerHost>${docker.host}</dockerHost>
            <!-- Docker镜像私服地址 -->
            <registry>${docker.registry}</registry>
            <!-- 认证信息 -->
            <authConfig>
              <push>
                <username>${docker.username}</username>
                <password>${docker.password}</password>
              </push>
            </authConfig>
            <images>
              <image>
                <!-- 镜像名称 -->
                <name>${docker.registry}/${docker.namespace}/${project.name}:${project.version}</name>
                <build>
                  <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                </build>
              </image>
            </images>
          </configuration>
        </plugin>
        <!-- 代码格式插件，默认使用spring规则，可运行maven命令进行项目格式化 -->
        <!-- https://github.com/spring-io/spring-javaformat/ -->
        <!-- 使用时需要添加一个【.springjavaformatconfig】文件到项目根目录 -->
        <plugin>
          <groupId>io.spring.javaformat</groupId>
          <artifactId>spring-javaformat-maven-plugin</artifactId>
          <version>${spring-javaformat-plugin.version}</version>
          <executions>
            <execution>
              <phase>validate</phase>
              <inherited>true</inherited>
              <goals>
                <goal>validate</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>

  <profiles>
    <profile>
      <id>dev</id>
      <properties>
        <profiles.active>dev</profiles.active>

        <nacos.username>nacos</nacos.username>
        <nacos.password>nacos</nacos.password>

        <docker.host>http://127.0.0.1:2375</docker.host>
        <docker.registry>127.0.0.1:8081</docker.registry>
        <docker.username>admin</docker.username>
        <docker.password>abc123</docker.password>
        <docker.namespace>lib</docker.namespace>
      </properties>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
  </profiles>
</project>
