spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.templating.spring.mustache.charset
  # org.springframework.boot.autoconfigure.mustache.MustacheProperties
  # Mustache配置
  mustache:
    enabled: true
    charset: UTF-8
    prefix: classpath:/templates/
    suffix: .mustache
    check-template-location: true
    view-names:
    request-context-attribute:
    servlet:
      cache: false
      allow-request-override: false
      allow-session-override: false
      content-type: text/html
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
    reactive:
      media-types:
        - text/html;charset=UTF-8
