spring:
  groovy:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.templating.spring.groovy.template.allow-request-override
    # org.springframework.boot.autoconfigure.groovy.template.GroovyTemplateProperties
    # Groovy template配置
    template:
      enabled: true
      cache: false
      content-type: text/html
      charset: UTF-8
      view-names:
      check-template-location: true
      prefix:
      suffix: .tpl
      request-context-attribute:
      expose-request-attributes: false
      expose-session-attributes: false
      allow-request-override: false
      allow-session-override: false
      expose-spring-macro-helpers: true
      resource-loader-path: classpath:/templates/
