spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.templating.spring.thymeleaf.cache
  # org.springframework.boot.autoconfigure.thymeleaf.ThymeleafProperties
  # Thymeleaf配置
  thymeleaf:
    enabled: true
    cache: true
    check-template: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    template-resolver-order:
    enable-spring-el-compiler: false
    render-hidden-markers-before-checkboxes: false
    view-names:
    excluded-view-names:
    servlet:
      content-type: text/html
      produce-partial-output-while-processing: true
    reactive:
      max-chunk-size: 0
      media-types:
      full-mode-view-names:
      chunked-mode-view-names:
