spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.templating.spring.freemarker.allow-request-override
  # org.springframework.boot.autoconfigure.freemarker.FreeMarkerProperties
  # FreeMarker配置
  freemarker:
    enabled: true
    cache: false
    content-type: text/html
    charset: UTF-8
    view-names:
    check-template-location: true
    prefix:
    suffix: .ftlh
    request-context-attribute:
    expose-request-attributes: false
    expose-session-attributes: false
    allow-request-override: false
    allow-session-override: false
    expose-spring-macro-helpers: true
    template-loader-path:
      - classpath:/templates/
    prefer-file-system-access: false
    settings:
