spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.kafka.admin.auto-create
  # org.springframework.boot.autoconfigure.kafka.KafkaProperties
  # Apache Kafka配置
  kafka:
    bootstrap-servers:
      - localhost:9092
    client-id:
    consumer:
      bootstrap-servers:
      client-id:
      enable-auto-commit:
      fetch-max-wait:
      fetch-min-size:
      group-id:
      heartbeat-interval:
      auto-commit-interval:
      auto-offset-reset:
      isolation-level: read_uncommitted
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records:
      ssl:
        protocol:
        key-password:
        key-store-type:
        key-store-key:
        key-store-location:
        key-store-password:
        key-store-certificate-chain:
        trust-store-type:
        trust-store-password:
        trust-store-location:
        trust-store-certificates:
      security:
        protocol:
      properties:
    producer:
      bootstrap-servers:
      client-id:
      acks:
      batch-size:
      buffer-memory:
      compression-type:
      retries:
      transaction-id-prefix:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      ssl:
        protocol:
        key-password:
        key-store-type:
        key-store-key:
        key-store-location:
        key-store-password:
        key-store-certificate-chain:
        trust-store-type:
        trust-store-password:
        trust-store-location:
        trust-store-certificates:
      security:
        protocol:
      properties:
    admin:
      client-id:
      fail-fast: false
      ssl:
        protocol:
        key-password:
        key-store-type:
        key-store-key:
        key-store-location:
        key-store-password:
        key-store-certificate-chain:
        trust-store-type:
        trust-store-password:
        trust-store-location:
        trust-store-certificates:
      security:
        protocol:
      properties:
    streams:
      bootstrap-servers:
      client-id:
      application-id:
      auto-startup: true
      cache-max-size-buffering:
      replication-factor:
      state-dir:
      ssl:
        protocol:
        key-password:
        key-store-type:
        key-store-key:
        key-store-location:
        key-store-password:
        key-store-certificate-chain:
        trust-store-type:
        trust-store-password:
        trust-store-location:
        trust-store-certificates:
      security:
        protocol:
      cleanup:
        on-startup: false
        on-shutdown: false
      properties:
    listener:
      type: single
      client-id:
      ack-mode:
      ack-count:
      ack-time:
      concurrency:
      poll-timeout:
      no-poll-threshold:
      idle-between-polls: 0
      idle-event-interval:
      idle-partition-event-interval:
      monitor-interval:
      log-container-config:
      missing-topics-fatal: false
      immediate-stop: false
      only-log-record-metadata: true
    ssl:
      protocol:
      key-password:
      key-store-type:
      key-store-key:
      key-store-location:
      key-store-password:
      key-store-certificate-chain:
      trust-store-type:
      trust-store-password:
      trust-store-location:
      trust-store-certificates:
    jaas:
      enabled: false
      login-module: com.sun.security.auth.module.Krb5LoginModule
      control-flag: required
      options:
    template:
      default-topic:
      transaction-id-prefix:
    security:
      protocol:
    retry:
      topic:
        enabled: false
        attempts: 3
        delay: 1s
        multiplier: 0.0
        max-delay: 0
        random-back-off: false
    properties:
