spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.rabbitmq.address-shuffle-mode
  # org.springframework.boot.autoconfigure.amqp.RabbitProperties
  # Rabbit配置
  rabbitmq:
    addresses:
    host: localhost
    port:
    username: guest
    password: guest
    virtual-host:
    address-shuffle-mode: none
    requested-heartbeat:
    requested-channel-max: 2047
    publisher-returns: false
    publisher-confirm-type:
    connection-timeout:
    channel-rpc-timeout: 10m
    cache:
      channel:
        size:
        checkout-timeout:
      connection:
        mode: channel
        size:
    listener:
      type: simple
      simple:
        auto-startup: true
        acknowledge-mode:
        prefetch:
        default-requeue-rejected:
        idle-event-interval:
        de-batching-enabled: true
        concurrency:
        max-concurrency:
        batch-size:
        missing-queues-fatal: true
        consumer-batch-enabled: false
        retry:
          enabled: false
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 1.0
          max-interval: 10000ms
          stateless: true
      direct:
        auto-startup: true
        acknowledge-mode:
        prefetch:
        default-requeue-rejected:
        idle-event-interval:
        de-batching-enabled: true
        consumers-per-queue:
        missing-queues-fatal: false
      stream:
        auto-startup: true
        native-listener: false
    template:
      mandatory:
      receive-timeout:
      reply-timeout:
      exchange:
      routing-key:
      default-receive-queue:
      retry:
        enabled: false
        max-attempts: 3
        initial-interval: 1000ms
        multiplier: 1.0
        max-interval: 10000ms
    ssl:
      enabled:
      algorithm:
      key-store:
      key-store-type: PKCS12
      key-store-password:
      key-store-algorithm: SunX509
      trust-store:
      trust-store-type: JKS
      trust-store-password:
      trust-store-algorithm: SunX509
      validate-server-certificate: true
      verify-hostname: true
    stream:
      host: localhost
      port: 5552
      name:
      username:
      password:
