spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.artemis.broker-url
  # org.springframework.boot.autoconfigure.jms.artemis.ArtemisProperties
  # ActiveMQ配置
  artemis:
    mode:
    broker-url: tcp://localhost:61616
    user:
    password:
    embedded:
      enabled: true
      server-id: 0
      persistent: false
      data-directory:
      cluster-password:
      queues:
      topics:
    pool:
      enabled: false
      block-if-full: true
      block-if-full-timeout: -1
      idle-timeout: 30s
      max-connections: 1
      max-sessions-per-connection: 500
      time-between-expiration-check: -1
      use-anonymous-producers: true
