spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.integration.spring.webservices.path
  # org.springframework.boot.autoconfigure.webservices.WebServicesProperties
  # Spring Web Services配置
  webservices:
    # 服务的基本URI路径。默认：/services
    path: /services
    # Servlet配置
    servlet:
      # 加载Spring Web Services servlet的启动优先级。默认：-1
      load-on-startup: -1
      # 要传递给Spring Web Services的Servlet init参数
      init:
