spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.jersey.application-path
  # org.springframework.boot.autoconfigure.jersey.JerseyProperties
  # Jersey配置
  jersey:
    # Jersey集成类型。默认：servlet。可选：servlet、filter
    type: servlet
    # 应用程序的基础URI路径。如果指定，则覆盖“@ApplicationPath”的值
    application-path:
    # Servlet配置
    servlet:
      # Servlet的启动优先级。默认：-1
      load-on-startup: -1
    # 过滤器配置
    filter:
      # 过滤器链顺序。默认：0
      order: 0
    # 传递给Servlet或者过滤器的初始化参数
    init:
