spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.graphql.cors.allow-credentials
  # org.springframework.boot.autoconfigure.graphql.GraphQlProperties
  # Spring GraphQL配置
  graphql:
    path: /graphql
    graphiql:
      enabled: false
      path: /graphiql
    schema:
      locations:
        - classpath:graphql/**/
      file-extensions:
        - .graphqls
        - .gqls
      introspection:
        enabled: true
      printer:
        enabled: false
    # org.springframework.boot.autoconfigure.graphql.GraphQlCorsProperties
    cors:
      allowed-methods:
      allowed-headers:
      allowed-origins:
      allowed-origin-patterns:
      allow-credentials:
      exposed-headers:
      max-age: 1800s
    websocket:
      path:
      connection-init-timeout: 60s
    rsocket:
      mapping:
