spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.webflux.base-path
  # org.springframework.boot.autoconfigure.web.reactive.WebFluxProperties
  # WebFlux配置
  webflux:
    base-path:
    static-path-pattern: /**
    webjars-path-pattern:
    format:
      date-time:
      date:
      time:
    # org.springframework.boot.autoconfigure.web.reactive.ReactiveMultipartProperties
    multipart:
      max-in-memory-size: 256KB
      max-headers-size: 10KB
      max-disk-usage-per-part: -1
      max-parts: -1
      streaming: false
      file-storage-directory:
      headers-charset: UTF-8
    hiddenmethod:
      filter:
        enabled: false
    problemdetails:
      enabled:
    session:
      cookie:
        same-site:
