spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.mvc.async.request-timeout
  # org.springframework.boot.autoconfigure.web.servlet.WebMvcProperties
  # Spring MVC配置
  mvc:
    # 静态资源的路径模式。默认：/**
    static-path-pattern: '/**'
    # 是否将TRACE请求分派给FrameworkServlet doService方法。默认：false
    dispatch-trace-request: false
    # 是否将OPTIONS请求分派给FrameworkServlet doService方法。默认：true
    dispatch-options-request: true
    # 在重定向中是否忽略“默认”model中的内容。默认：true
    ignore-default-model-on-redirect: true
    # 是否在每个请求的末尾发布ServletRequestHandledEvent。默认：true
    publish-request-handled-events: true
    # 如果找不到处理程序来处理请求，是否应引发“NoHandlerFoundException”。默认：false
    throw-exception-if-no-handler-found: true
    # 是否允许在日志中记录请求详细信息。（可能潜在的敏感内容）默认：false
    log-request-details: false
    # 是否日志记录解决的异常信息。默认：false
    log-resolved-exception: false
    # 消息code的格式设置策略。可选：postfix_error_code、prefix_error_code
    message-codes-resolver-format:
    # WebJar资源路径
    webjars-path-pattern:
    # Servlet配置
    servlet:
      # Dispatcher Servlet路径。默认：/
      path: /
      # Dispatcher Servlet启动优先级。默认：-1
      load-on-startup: -1
    # 视图配置
    view:
      # MVC视图前缀
      prefix:
      # MVC视图后缀
      suffix:
    # 异步请求配置
    async:
      # 异步请求处理的超时时间
      request-timeout:
    # 格式配置
    format:
      # 要使用的日期时间格式
      date-time: 'yyyy-MM-dd HH:mm:ss'
      # 要使用的日期格式
      date: 'yyyy-MM-dd'
      # 要使用的时间格式
      time: 'HH:mm:ss'
    # 内容协商配置
    contentnegotiation:
      # 是否使用请求参数（默认为“format”）来确定请求的媒体类型。默认：false
      favor-parameter: false
      # 启用“favor-parameter”时要使用的查询参数名称
      parameter-name: format
      # 是否使用URL路径中的扩展名来确定请求的媒体类型。如果启用，则请求“/users.pdf”将被解释为“application/pdf”请求，而不考虑“Accept”标头。默认：false
      favor-path-extension: false
      # 将文件扩展名映射到媒体类型以进行内容协商
      media-types:
        yml: text/yaml
    # 路径匹配配置
    pathmatch:
      # 选择将请求路径与已注册的映射进行匹配的策略。默认：path_pattern_parser。可选：path_pattern_parser、ant_path_matcher
      matching-strategy: path_pattern_parser
      # 将模式与请求匹配时是否使用后缀模式匹配（“.*”）。如果启用，映射到“/users”的方法也与“/users.*”匹配。启用此选项与PathPatternParser匹配策略不兼容。默认：false（已弃用）
      use-suffix-pattern: false
      # 后缀模式匹配是否应仅适用于使用“spring.mvc.contentnegotiation.media-types.*”注册的扩展。默认：false（已弃用）
      use-registered-suffix-pattern: false
    # hidden方法配置
    hiddenmethod:
      # 过滤器配置
      filter:
        # 是否启用Spring的HiddenHttpMethodFilter。默认：false
        enabled: false
    # 问题详情
    problemdetails:
      # 是否启用RFC 7807问题详细信息支持
      enabled:
