spring:
  # Servlet配置
  servlet:
    # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.servlet.multipart.enabled
    # org.springframework.boot.autoconfigure.web.servlet.MultipartProperties
    #  MultipartConfigElement配置
    multipart:
      # 是否开启multipart上传支持。默认：true
      enabled: true
      # 上传文件的中间位置
      location:
      # 是否在访问文件或参数时延迟解析multipart请求。默认：false
      resolve-lazily: false
      # 最大文件大小。默认：1MB
      max-file-size: 1MB
      # 最大请求大小。默认：10MB
      max-request-size: 10MB
      # 超过此阈值后，文件将写入磁盘。默认：0
      file-size-threshold: 0
