spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.web.spring.web.locale
  # org.springframework.boot.autoconfigure.web.WebProperties
  # Web配置
  web:
    locale:
    locale-resolver: accept_header
    resources:
      static-locations:
        - classpath:/META-INF/resources/
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true
      cache:
        period:
        use-last-modified: true
        cachecontrol:
          max-age:
          cache-private:
          cache-public:
          no-cache:
          no-store:
          no-transform:
          must-revalidate:
          proxy-revalidate:
          stale-while-revalidate:
          stale-if-error:
          s-max-age:
      chain:
        enabled:
        cache: true
        compressed: false
        strategy:
          fixed:
            enabled: false
            paths:
              - /**
            version:
          content:
            enabled: false
            paths:
              - /**
