spring:
  datasource:
    # 动态数据源配置
    # com.baomidou.dynamic.datasource.spring.boot.autoconfigure.DynamicDataSourceProperties
    dynamic:
      primary: master
      # 是否开启seata
      seata: false
      # 是否使用严格模式（没有获取到指定的数据源直接报错）
      strict: false
      # SQL监控（影响性能，生产上请勿开启）
      p6spy: true
      aop:
        # 是否开启AOP支持
        enabled: true
        # 是否只代理public方法
        allowed-public-only: true
      # Druid数据源公共配置
      druid:
        initial-size: 10
        min-idle: 5
        max-active: 15
        async-init: true
        max-wait: 6000
        min-evictable-idle-time-millis: 600000
        max-evictable-idle-time-millis: 900000
        time-between-eviction-runs-millis: 60000
        validation-query: "SELECT 'x'"
        validation-query-timeout: 2
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
        filters: slf4j
        pool-prepared-statements: false
        max-pool-prepared-statement-per-connection-size: -1
        connection-properties:
          druid.stat.mergeSql: true
          druid.stat.slowSqlMillis: 5000
        stat:
          enabled: true
          urlPattern: '/druid/*'
          allow: 127.0.0.1,192.168.0.100
          loginUsername: admin
          loginPassword: druid
          resetEnable: true
      # 数据源
      datasource:
        mysql:
          username: root
          password: mysql
          url: 'jdbc:mysql://192.168.0.100:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false'
          driverClassName: com.mysql.cj.jdbc.Driver
          poolName: 'Datasource-Pool-MySQL'
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initialSize: 20
            minIdle: 10
            maxActive: 30
            validationQuery: 'SELECT 1 FROM DUAL'
            poolPreparedStatements: false
            filters: stat,wall,slf4j
        oracle:
          username: sys
          password: oracle
          url: jdbc:oracle:thin:@192.168.0.100:1521:orcl
          driverClassName: oracle.jdbc.driver.OracleDriver
          poolName: 'Datasource-Pool-Oracle'
          type: com.alibaba.druid.pool.DruidDataSource
          druid:
            initialSize: 20
            minIdle: 10
            maxActive: 30
            validationQuery: 'SELECT 1'
            poolPreparedStatements: true
            maxPoolPreparedStatementPerConnectionSize: 100
            filters: stat,wall,slf4j