spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.security.spring.security.filter.dispatcher-types
  # org.springframework.boot.autoconfigure.security.SecurityProperties
  # Spring Security配置
  security:
    filter:
      order: -100
      dispatcher-types:
        - async
        - error
        - request
    user:
      name: user
      password:
      roles:
    oauth2:
      # org.springframework.boot.autoconfigure.security.oauth2.resource.OAuth2ResourceServerProperties
      resourceserver:
        jwt:
          jwk-set-uri:
          jws-algorithms:
            - RS256
          issuer-uri:
          public-key-location:
          audiences:
        opaquetoken:
          client-id:
          client-secret:
          introspection-uri:
      # org.springframework.boot.autoconfigure.security.oauth2.client.OAuth2ClientProperties
      client:
        provider:
        registration:
    saml2:
      # org.springframework.boot.autoconfigure.security.saml2.Saml2RelyingPartyProperties
      relyingparty:
        registration:
