### \u9ED8\u8BA4\u914D\u7F6E\uFF0C\u53C2\u89C1\uFF1Aquartz-2.3.2.jar!\org\quartz\quartz.properties
### \u914D\u7F6E\u8BF4\u660E\uFF0C\u53C2\u89C1\uFF1Ahttp://www.quartz-scheduler.org/documentation/quartz-2.3.0/configuration/
### Main
org.quartz.scheduler.instanceName=QuartzScheduler
org.quartz.scheduler.instanceId=NON_CLUSTERED
# \u5B9E\u4F8BId\u751F\u6210\u5668\uFF0C\u8BE6\u60C5\u53C2\u8003\uFF1Aorg.quartz.spi.InstanceIdGenerator\u53CA\u5176\u5B50\u7C7B
org.quartz.scheduler.instanceIdGenerator.class=org.quartz.simpl.SimpleInstanceIdGenerator
# \u8C03\u5EA6\u5668\u7EBF\u7A0B\u540D\u79F0\uFF0C\u9ED8\u8BA4\uFF1AinstanceName + '_QuartzSchedulerThread'
org.quartz.scheduler.threadName=
org.quartz.scheduler.makeSchedulerThreadDaemon=false
org.quartz.scheduler.threadsInheritContextClassLoaderOfInitializer=false
org.quartz.scheduler.idleWaitTime=30000
org.quartz.scheduler.dbFailureRetryInterval=15000
org.quartz.scheduler.classLoadHelper.class=org.quartz.simpl.CascadingClassLoadHelper
org.quartz.scheduler.jobFactory.class=org.quartz.simpl.PropertySettingJobFactory
org.quartz.context.key.SOME_KEY=none
org.quartz.scheduler.userTransactionURL='java:comp/UserTransaction'
org.quartz.scheduler.wrapJobExecutionInUserTransaction=false
org.quartz.scheduler.skipUpdateCheck=false
org.quartz.scheduler.batchTriggerAcquisitionMaxCount=1
org.quartz.scheduler.batchTriggerAcquisitionFireAheadTimeWindow=0

### ThreadPool
# \u7EBF\u7A0B\u6C60\u7C7B\uFF0C\u5FC5\u987B\uFF0C\u9ED8\u8BA4\uFF1Anull
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
# \u7EBF\u7A0B\u6C60\u7EBF\u7A0B\u6570\uFF0C\u5FC5\u987B\uFF0C\u9ED8\u8BA4\uFF1A-1
org.quartz.threadPool.threadCount=
org.quartz.threadPool.threadPriority=Thread.NORM_PRIORITY
## \u7B80\u5355\u7EBF\u7A0B\u6C60[org.quartz.simpl.SimpleThreadPool]
# \u628A\u7EBF\u7A0B\u53D8\u6210\u5B88\u62A4\u7EBF\u7A0B
org.quartz.threadPool.makeThreadsDaemons=false
org.quartz.threadPool.threadsInheritGroupOfInitializingThread=true
org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread=true
# \u7EBF\u7A0B\u540D\u79F0\u524D\u7F00\uFF0C\u9ED8\u8BA4\uFF1A[Scheduler Name] + '_Worker'
org.quartz.threadPool.threadNamePrefix=


## DataSource
org.quartz.jobStore.dataSource=quartz
# \u6570\u636E\u5E93\u8FDE\u63A5\u6C60\u63D0\u4F9B\u8005\u5B9E\u73B0\uFF0C\u9ED8\u8BA4\uFF1Ac3p0\uFF0C\u8BE6\u60C5\u53C2\u8003\uFF1Aorg.quartz.utils.ConnectionProvider\u53CA\u5176\u5B50\u7C7B
org.quartz.dataSource.quartz.connectionProvider.class=
org.quartz.dataSource.quartz.driver=com.mysql.cj.jdbc.Driver
org.quartz.dataSource.quartz.URL=jdbc:mysql://localhost:3306/test
org.quartz.dataSource.quartz.user=root
org.quartz.dataSource.quartz.password=admin
org.quartz.dataSource.quartz.maxConnection=30