<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.zero</groupId>
    <artifactId>common</artifactId>
    <version>1.0.0</version>
  </parent>

  <artifactId>common-core</artifactId>
  <version>1.0.0</version>

  <packaging>jar</packaging>

  <name>common-core</name>
  <description>Demo project for Common Core</description>

  <dependencies>
    <!-- ######################################################## Spring Cloud Alibaba ######################################################## -->
    <!-- nacos discovery（服务注册/发现） -->
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- nacos config（配置中心） -->
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- sentinel（服务熔断） -->
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-alibaba-sentinel-datasource</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-alibaba-sentinel-gateway</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- sentinel支持多种持久化存储：nacos，apollo，redis，zk，consul... -->
    <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-datasource-nacos</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 用于解决sentinel高版本下流控链路不生效的问题 -->
    <dependency>
      <groupId>com.alibaba.csp</groupId>
      <artifactId>sentinel-web-servlet</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- seata（分布式事务） -->
    <dependency>
      <groupId>com.alibaba.cloud</groupId>
      <artifactId>spring-cloud-starter-alibaba-seata</artifactId>
      <scope>provided</scope>
      <exclusions>
        <exclusion>
          <artifactId>druid</artifactId>
          <groupId>com.alibaba</groupId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- ######################################################## Spring Cloud Netflix ######################################################## -->
    <!-- eureka（服务注册/发现） -->
    <!-- Netflix在Spring Cloud Dependencies中唯一坚挺的组件，但是留给Eureka的时间也不多了 -->
    <!-- 客户端 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 服务端 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-eureka-server</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- hystrix（服务熔断） -->
    <!-- Spring Cloud 2020.0版本以后，Hystrix已从Spring Cloud Dependencies中删除 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
      <version>2.2.10.RELEASE</version>
      <scope>provided</scope>
    </dependency>
    <!-- ribbon（负载均衡） -->
    <!-- Spring Cloud 2020.0版本以后，Ribbon已从Spring Cloud Dependencies中删除 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-ribbon</artifactId>
      <version>2.2.10.RELEASE</version>
      <scope>provided</scope>
    </dependency>
    <!-- zuul（网关） -->
    <!-- Spring Cloud 2020.0版本以后，Zuul已从Spring Cloud Dependencies中删除 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
      <version>2.2.10.RELEASE</version>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Spring Cloud ######################################################## -->
    <!-- config（配置中心） -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-config</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- openfeign（服务调用） -->
    <!--
        Feign 和 OpenFeign：
        feign原本是Netflix提供的一个轻量级RESTful的HTTP服务客户端，内置了ribbon，用来做客户端负载均衡，去调用服务注册中心的服务
        于是基于feign提供了spring-cloud-starter-feign组件，成为spring官方推荐
        后来，在2019年Netflix不再维护feign，feign转由社区维护，并更名为openfeign
        于是又基于openfeign进行包装，并在Spring Cloud Netflix Feign的基础上支持了SpringMVC的注解
        因此spring-cloud-starter-openfeign代替spring-cloud-starter-feign组件，成为官方维护、推荐组件
    -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-openfeign</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- feign（服务调用） -->
    <!-- 在Spring Cloud Finchley及以上版本已过期，被spring-cloud-starter-openfeign组件替代 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-feign</artifactId>
      <version>1.4.7.RELEASE</version>
      <scope>provided</scope>
    </dependency>
    <!-- resilience4j（服务熔断） -->
    <!-- Spring Cloud 2020.0版本以后，Resilience4J正式替换Hystrix，但目前Resilience4J还比较小众 -->
    <!-- 非响应式 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 响应式 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- loadbalancer（负载均衡） -->
    <!-- Spring Cloud 2020.0版本以后，官方默认推荐使用Spring Cloud Loadbalancer正式替换Ribbon，并成为了Spring Cloud负载均衡器的唯一实现 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-loadbalancer</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- gateway（网关） -->
    <!--
        Zuul 1.x（第一代Zuul）官宣会进行优化性能问题，结果Netflix跳票
        spring官方不得不推出新一代网关Gateway，此时Spring Cloud Gateway就已经替换了Zuul
        后来Netflix发布Zuul 2.x，又开始抢占了一部分市场
        再后来Zuul进入维护阶段，到Spring Cloud 2020.0版本以后，Zuul已从Spring Cloud中删除
    -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-gateway</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- bootstrap（Bootstrap配置文件支持） -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-bootstrap</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- sleuth（链路追踪器） -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-sleuth</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- zipkin（链路分析器） -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-sleuth-zipkin</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 已过时 -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-starter-zipkin</artifactId>
      <version>2.2.8.RELEASE</version>
      <scope>provided</scope>
    </dependency>
    <!-- commons（微服务公共组件） -->
    <dependency>
      <groupId>org.springframework.cloud</groupId>
      <artifactId>spring-cloud-commons</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Other Cloud（其他微服务组件） ######################################################## -->
    <!-- apollo（配置中心） -->
    <dependency>
      <groupId>com.ctrip.framework.apollo</groupId>
      <artifactId>apollo-client-config-data</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- xxl-job（分布式任务调度） -->
    <dependency>
      <groupId>com.xuxueli</groupId>
      <artifactId>xxl-job-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- spring-file-storage（文件存储） -->
    <dependency>
      <groupId>org.dromara.x-file-storage</groupId>
      <artifactId>x-file-storage-spring</artifactId>
    </dependency>
    <!-- jetchache（缓存）-->
    <dependency>
      <groupId>com.alicp.jetcache</groupId>
      <artifactId>jetcache-starter-redis-lettuce</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- minio（分布式存储） -->
    <dependency>
      <groupId>io.minio</groupId>
      <artifactId>minio</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- tx-lcn（分布式事务） -->
    <!-- 事务管理器（服务端） -->
    <dependency>
      <groupId>com.codingapi.txlcn</groupId>
      <artifactId>txlcn-tm</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 事务参与方（客户端） -->
    <dependency>
      <groupId>com.codingapi.txlcn</groupId>
      <artifactId>txlcn-tc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- power-job（分布式任务调度） -->
    <dependency>
      <groupId>tech.powerjob</groupId>
      <artifactId>powerjob-worker-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- redisson（分布式锁） -->
    <dependency>
      <groupId>org.redisson</groupId>
      <artifactId>redisson-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Spring Boot ######################################################## -->
    <!-- boot starter -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- logging [slf4j+logback]（日志） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- log4j2（日志） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-log4j2</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- log4j2异步日志依赖 -->
    <dependency>
      <groupId>com.lmax</groupId>
      <artifactId>disruptor</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- web（非响应式web） -->
    <!-- 请注意：web和webflux组件无法共存 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- webflux（响应式web） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-webflux</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- web-services -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web-services</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- websocket -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-websocket</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- actuator（程序监控/管理） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- mail（邮件） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mail</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- freemarker（模板引擎） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-freemarker</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- thymeleaf（模板引擎） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-thymeleaf</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- groovy-templates（模板引擎） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-groovy-templates</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- mustache（模板引擎） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-mustache</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- validation（参数检验） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- jdbc -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- cache（缓存） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-cache</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- aop（切面编程支持） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-aop</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- activemq（消息队列） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-activemq</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- amqp [Rabbit MQ]（消息队列） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-amqp</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.amqp</groupId>
      <artifactId>spring-rabbit-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- quartz（定时任务） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-quartz</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- netty -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-reactor-netty</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <scope>test</scope>
    </dependency>
    <!-- security（安全框架） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** spring data ******************************************************** -->
    <!-- data jdbc -->
    <!-- jdbc 升级版，提供CurdRepository快捷开发接口 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jdbc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data jpa -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data redis -->
    <!-- 非响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data mongodb -->
    <!-- 非响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data neo4j -->
    <!-- Neo4j：高性能的nosql图形数据库 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-neo4j</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data r2dbc（响应式） -->
    <!-- R2DBC(Reactive Relational Database Connectivity) -->
    <!-- 为数据库操作提供响应式支持，使用完全无阻塞驱动程序创建数据库链接，为SQL数据库创建响应式API -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-r2dbc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data cassandra -->
    <!-- 非响应式 -->
    <!-- Apache Cassandra：分布式NoSQL大数据量数据库 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-cassandra</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-cassandra-reactive</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data couchbase -->
    <!-- 非响应式 -->
    <!-- Couchbase：分布式NoSQL文档数据库 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-couchbase</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 响应式 -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-couchbase-reactive</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- data elasticsearch -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-elasticsearch</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** spring batch ******************************************************** -->
    <!-- batch（批处理） -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-batch</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.batch</groupId>
      <artifactId>spring-batch-test</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- ******************************************************** spring shell ******************************************************** -->
    <!-- shell（脚本） -->
    <dependency>
      <groupId>org.springframework.shell</groupId>
      <artifactId>spring-shell-starter</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** spring security ******************************************************** -->
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-authorization-server</artifactId>
      <version>0.4.2</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-oauth2-core</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Other Boot（其他启动器） ######################################################## -->
    <!-- druid（数据源） -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>druid-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- arthas（线上监控诊断） -->
    <dependency>
      <groupId>com.taobao.arthas</groupId>
      <artifactId>arthas-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- dynamic-datasource（动态数据源） -->
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>dynamic-datasource-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- mybatis（数据持久层（ORM）框架） -->
    <dependency>
      <groupId>org.mybatis.spring.boot</groupId>
      <artifactId>mybatis-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- MP（mybatis增强组件） -->
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- MyBatis-Flex（mybatis增强组件） -->
    <dependency>
      <groupId>com.mybatis-flex</groupId>
      <artifactId>mybatis-flex-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- MyBatis-Flex提供的APT服务，建议不要使用此方式，而是通过插件配置到annotationProcessorPaths -->
    <dependency>
      <groupId>com.mybatis-flex</groupId>
      <artifactId>mybatis-flex-processor</artifactId>
      <version>${mybatis-flex.version}</version>
      <scope>provided</scope>
    </dependency>
    <!-- shiro（安全框架） -->
    <dependency>
      <groupId>org.apache.shiro</groupId>
      <artifactId>shiro-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- jasypt（配置加密解密） -->
    <dependency>
      <groupId>com.github.ulisesbocchio</groupId>
      <artifactId>jasypt-spring-boot-starter</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>de.codecentric</groupId>
      <artifactId>spring-boot-admin-server</artifactId>
    </dependency>
    <!-- ######################################################## Spring Framework ######################################################## -->
    <!-- context-support（上下文增强） -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context-support</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- retry（重试） -->
    <dependency>
      <groupId>org.springframework.retry</groupId>
      <artifactId>spring-retry</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** spring session ******************************************************** -->
    <!-- 用redis存储session -->
    <dependency>
      <groupId>org.springframework.session</groupId>
      <artifactId>spring-session-data-redis</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 用数据库存储session -->
    <dependency>
      <groupId>org.springframework.session</groupId>
      <artifactId>spring-session-jdbc</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Spring Other（Spring官方依赖组件） ######################################################## -->
    <!-- caffeine（本地缓存） -->
    <dependency>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>caffeine</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- aspectjweaver（解析切入点表达式） -->
    <dependency>
      <groupId>org.aspectj</groupId>
      <artifactId>aspectjweaver</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- gson（json解析） -->
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- commons-dbcp2（数据库连接池） -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-dbcp2</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- commons-codec（加密解密） -->
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- commons-lang3（工具包） -->
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-lang3</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** JDBC ******************************************************** -->
    <!-- mysql（JDBC）（过时） -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- 新版MySQL JDBC，从MySQL 8.0.31开始 -->
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <version>${mysql.version}</version>
      <scope>provided</scope>
    </dependency>
    <!-- mysql r2dbc 的实现 -->
    <dependency>
      <groupId>dev.miku</groupId>
      <artifactId>r2dbc-mysql</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- ojdbc8（JDBC） -->
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc8</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- mariadb（JDBC） -->
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- mariadb r2dbc 的实现 -->
    <dependency>
      <groupId>org.mariadb</groupId>
      <artifactId>r2dbc-mariadb</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- h2（JDBC） -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- h2 r2dbc 的实现 -->
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-h2</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- sqlserver（JDBC） -->
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- sqlserver r2dbc 的实现 -->
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-mssql</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- postgresql（JDBC） -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- postgresql r2dbc 的实现 -->
    <dependency>
      <groupId>io.r2dbc</groupId>
      <artifactId>r2dbc-postgresql</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- db2（JDBC） -->
    <dependency>
      <groupId>com.ibm.db2</groupId>
      <artifactId>jcc</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- derby（JDBC） -->
    <dependency>
      <groupId>org.apache.derby</groupId>
      <artifactId>derby</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- hsqldb（JDBC） -->
    <dependency>
      <groupId>org.hsqldb</groupId>
      <artifactId>hsqldb</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** redis client ******************************************************** -->
    <!-- lettuce（Redis客户端） -->
    <!-- 线程安全 -->
    <dependency>
      <groupId>io.lettuce</groupId>
      <artifactId>lettuce-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- jedis（Redis客户端） -->
    <!-- 线程不安全 -->
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** micrometer（监控） ******************************************************** -->
    <!-- prometheus整合集成micrometer -->
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- r2dbc整合集成micrometer -->
    <dependency>
      <groupId>org.springframework.experimental</groupId>
      <artifactId>r2dbc-micrometer-spring-boot</artifactId>
      <version>1.0.1</version>
      <scope>provided</scope>
    </dependency>

    <!-- ******************************************************** http client ******************************************************** -->
    <!-- okhttp（Http客户端） -->
    <dependency>
      <groupId>com.squareup.okhttp3</groupId>
      <artifactId>okhttp</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- httpclient（Http客户端） -->
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpclient</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Parent Other（父项目其他依赖组件） ######################################################## -->
    <!-- hutool（工具集） -->
    <dependency>
      <groupId>cn.hutool</groupId>
      <artifactId>hutool-all</artifactId>
    </dependency>
    <!-- guava（工具集） -->
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.penggle</groupId>
      <artifactId>kaptcha</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- transmittable-thread-local（TTL） -->
    <!-- 处理父子线程变量不能共用的情况 -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>transmittable-thread-local</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- fastjson（json解析） -->
    <dependency>
      <groupId>com.alibaba</groupId>
      <artifactId>fastjson</artifactId>
      <scope>provided</scope>
    </dependency>
    <!-- common-data -->
    <dependency>
      <groupId>org.zero</groupId>
      <artifactId>common-data</artifactId>
      <scope>provided</scope>
    </dependency>

    <!-- ######################################################## Other（本项目其他依赖组件） ######################################################## -->
    <!-- commons-io -->
    <dependency>
      <groupId>commons-io</groupId>
      <artifactId>commons-io</artifactId>
      <version>2.11.0</version>
      <scope>provided</scope>
    </dependency>
    <!-- commons-dbutils（数据库工具） -->
    <dependency>
      <groupId>commons-dbutils</groupId>
      <artifactId>commons-dbutils</artifactId>
      <version>1.7</version>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
