spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.messages.always-use-message-format
  # org.springframework.boot.autoconfigure.context.MessageSourceProperties
  # 消息源配置（i18n）
  messages:
    # 是否始终应用MessageFormat规则，甚至解析不带参数的消息。 默认：false
    always-use-message-format: false
    # 消息源基名。默认：messages
    basename: messages
    # 加载的Message bundle文件缓存持续时间，没有单位时默认为秒
    cache-duration:
    # Message bundle编码
    encoding: UTF-8
    # 如果未找到特定区域设置的文件，是否回退到系统区域设置。默认：true
    fallback-to-system-locale: true
    # 是否使用消息代码作为默认消息，而不是抛出“NoSuchMessageException”。建议仅在开发期间使用。默认：true
    use-code-as-default-message: false
