spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.info.build.encoding
  # org.springframework.boot.autoconfigure.info.ProjectInfoProperties
  # 项目信息配置
  info:
    # 构建信息配置
    build:
      # 文件编码。默认：UTF-8
      encoding: UTF-8
      # 生成的build-info.properties文件的位置。默认：classpath:META-INF/build-info.properties
      location: classpath:META-INF/build-info.properties
    # Git信息配置
    git:
      # 文件编码。默认：UTF-8
      encoding: UTF-8
      # 生成的git.properties文件的位置。默认：classpath:META-INF/git.properties
      location: classpath:git.properties
