spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.jmx.default-domain
  # org.springframework.boot.autoconfigure.jmx.JmxProperties
  # JMX配置
  jmx:
    # 是否向JMX域公开管理Bean
    enabled: false
    # 是否应确保运行时对象名称的唯一性
    unique-names: false
    # MBeanServer bean名称
    server: mbeanServer
    # JMX域名
    default-domain:
