# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.debug
# 是否启用调试日志。默认：false
debug: false

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.trace
# 是否开启追踪日志。默认：false
trace: false

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.info
# 要暴露到端点的属性
# 需要结合management.endpoints.web.exposure.include=info配置项
info:
  app: ${spring.application.name}

# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.aop.auto
spring:
  # 应用程序必须使用的预期字符编码
  mandatory-file-encoding:
  # AOP配置
  aop:
    # 是否开启AspectJ自动代理。默认：true
    auto: true
    # 是否要创建基于子类（CGLIB）的代理（true），而不是基于标准Java接口的代理（false）。默认：true
    proxy-target-class: true
  # 应用程序配置
  application:
    # 应用程序名称
    name: @artifactId@
    # 应用程序管理功能配置
    admin:
      # 是否启用程序的管理功能。默认：false
      enabled: false
      # 应用程序管理MBean的JMX名称。默认：org.springframework.boot:type=Admin,name=SpringApplication
      jmx-name: 'org.springframework.boot:type=Admin,name=SpringApplication'
  # 自动装配配置
  autoconfigure:
    # 要排除的自动配置类
    exclude:
  # BeanInfo类配置
  beaninfo:
    # 是否跳过BeanInfo类的搜索。默认：true
    ignore: true
  # org.springframework.boot.autoconfigure.codec.CodecProperties
  # reactive编码配置
  codec:
    # 是否在DEBUG级别记录表单数据，在TRACE级别记录header。默认：false
    log-request-details: false
    # 限制每当需要聚合输入流时可以缓冲的字节数。仅适用于自动配置的WebFlux服务器和WebClient实例。默认情况下，未设置此项，在这种情况下，将应用单个编解码器默认值。默认情况下，大多数编解码器限制为256K。
    max-in-memory-size:
  # org.springframework.boot.autoconfigure.context.LifecycleProperties
  # 生命周期处理配置
  lifecycle:
    # 关闭任何阶段（具有相同“阶段”值的SmartLifecycle Bean组）的超时。默认：30s
    timeout-per-shutdown-phase: 30s
  # 输出配置
  output:
    # ANSI配置
    ansi:
      # ANSI输出。默认：detect。可选：detect、never、always
      enabled: detect
  # 进程标识符配置
  pid:
    # PID文件位置
    file:
    # 是否直接失败在写入报错的时候
    fail-on-write-error:
  # 配置文件配置（已过时，使用spring.config.activate代替）
  profiles:
    # 激活的配置文件
    active:
    # 默认的配置文件。如果没有配置文件处于激活状态，要启用的配置文件的名称
    default:
    # 无条件激活的配置文件
    include:
    # 配置文件组
    group:
  # Reactor配置
  reactor:
    # Debug Agent配置
    debug-agent:
      # 当存在reactor-tools时，是否启用Reactor Debug Agent。默认：true
      enabled: true
    # 堆栈跟踪模式配置
    stacktrace-mode:
      # 是否在运行时收集堆栈跟踪信息。默认：false（已弃用，使用spring.reactor.debug-agent.enabled代替）
      enabled: false
    # Reactor Netty配置
    netty:
      # 关闭资源之前要等待的时间
      shutdown-quiet-period:
  # SSL配置（请勿使用，已移除）
  ssl:
    # SSL Bundle配置
    bundle:
      # Java密钥库SSL信任材料
      jks:
      # PEM编码的SSL信任材料
      pem:
