spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.task.execution.pool.allow-core-thread-timeout
  # 任务配置
  task:
    # org.springframework.boot.autoconfigure.task.TaskExecutionProperties
    # 任务执行配置
    execution:
      # 线程池配置
      pool:
        # 核心线程数。默认：8
        core-size: 8
        # 最大线程数。默认：Integer.MAX_VALUE
        max-size:
        # 最大线程数。默认：Integer.MAX_VALUE
        queue-capacity:
        # 是否允许核心线程超时。默认：true
        allow-core-thread-timeout: true
        # 线程在终止之前可以保持空闲状态的时间限制。默认：60s
        keep-alive: 60s
      # 新创建线程的名称前缀。默认：task-
      thread-name-prefix: task-
      # 关闭配置
      shutdown:
        # 是否在关闭时等待计划任务完成。默认：false
        await-termination: false
        # 等待计划任务完成的超时时间
        await-termination-period:
    # org.springframework.boot.autoconfigure.task.TaskSchedulingProperties
    # 任务计划配置
    scheduling:
      # 线程池配置
      pool:
        # 允许的最大线程数。默认：1
        size: 1
      # 新创建线程的名称前缀。默认：scheduling-
      thread-name-prefix: scheduling-
      # 关闭配置
      shutdown:
        # 是否在关闭时等待计划任务完成。默认：false
        await-termination: false
        # 等待计划任务完成的超时时间
        await-termination-period:
