spring:
  # https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.banner.charset
  # banner配置
  banner:
    # banner文件编码。默认：UTF-8
    charset: UTF-8
    # banner文件位置。默认：classpath:banner.txt
    location: classpath:banner.txt
    # banner图像文件配置
    image:
      # ANSI颜色的位深度。支持的值为4（16 色）或8（256 色）。默认：4
      bitdepth: 4
      # banner图像的高度（以字符为单位）。默认基于图像高度
      height:
      # banner图像的宽度（以字符为单位）。默认：76
      width: 76
      # 是否应针对深色终端主题反转图像。默认：false
      invert: false
      # banner图像文件位置，默认：classpath:banner.gif
      location: classpath:banner.gif
      # 左侧图像边距（以字符为单位）。默认：2
      margin: 2
      # 渲染图像时使用的像素模式。默认：text。可选：text、block
      pixelmode: text
